name: release

on:
  push:
    branches:
      - main
      - develop
      - release
      - release/*
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Force build as pre-release"
        required: false
        default: false
        type: boolean

permissions: write-all

jobs:
  release:
    uses: netexknowledge/.github/.github/workflows/release-reusable.yml@release-reusable#v1
    with:
      prerelease: ${{ github.event.inputs.prerelease || 'false' }}
    secrets: inherit
