name: "sync-from-main"

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [semantic-release-main]
  workflow_dispatch:

permissions: write-all

jobs:
  sync-to-develop:
    uses: netexknowledge/.github/.github/workflows/sync-with-branch-reusable.yml@sync-with-branch-reusable#v1
    with:
      from: "main"
      to: "develop"
    secrets: inherit

  sync-to-release:
    if:
    uses: netexknowledge/.github/.github/workflows/sync-with-branch-reusable.yml@sync-with-branch-reusable#v1
    with:
      from: "main"
      to: "release"
    secrets: inherit
